version: '3.9'

services:
  todo:
    restart: always
    env_file:
      - ./.env
    build: ./
    command: app
    ports:
      - "8000:${PORT}"
    depends_on:
      db:
        condition: service_healthy

  db:
    restart: always
    image: postgres:latest
    ports:
      - 5438:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_DB=${DB_NAME}